development:
  adapter: mysql2
  encoding: utf8
  database: yukkuri_dev
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: yukkuri_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: yukkuri
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
